const $ = id => document.getElementById(id);
const KEY_CFG="taikai_voice_cfg_v1",KEY_REC="taikai_voice_rec_v1",KEY_QUEUE="taikai_voice_queue_v1";
let cfg={event:"大会名未設定",date:"",mode:"MARATHON",point:"地点未設定",staff:"",top:"",endpoint:""},records=[],sendQueue=[],ok=0,muri=0,recognition=null,listening=false,restartTimer=null,deferredInstall=null,isSending=false;
function load(){try{Object.assign(cfg,JSON.parse(localStorage.getItem(KEY_CFG)||"{}"))}catch{}try{records=JSON.parse(localStorage.getItem(KEY_REC)||"[]")}catch{records=[]}ok=records.filter(r=>r.recognized&&!r.cancelled).length;muri=records.filter(r=>!r.recognized&&!r.cancelled).length;try{sendQueue=JSON.parse(localStorage.getItem(KEY_QUEUE)||"[]")}catch{sendQueue=[]}render();processQueue()}
function save(){localStorage.setItem(KEY_CFG,JSON.stringify(cfg));localStorage.setItem(KEY_REC,JSON.stringify(records));localStorage.setItem(KEY_QUEUE,JSON.stringify(sendQueue))}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':'&quot;',"'":"&#39;"}[c]))}function now(){return new Date().toLocaleTimeString("ja-JP",{hour12:false})}
function updateCountdown(){$("countdown").textContent=cfg.top?`TOP予想 ${cfg.top} ${countdownText()}`:"TOP予想：未設定"}
function render(){$("event").textContent=cfg.event+(cfg.date?` ${cfg.date}`:"");$("point").textContent=(cfg.mode==="EKIDEN"?"駅伝":"マラソン")+" "+cfg.point;$("staff").textContent="担当："+(cfg.staff||"未設定");$("modeBadge").textContent=cfg.mode==="EKIDEN"?"駅伝":"マラソン";updateCountdown();$("okCount").textContent=ok;$("muriCount").textContent=muri;$("totalCount").textContent=ok+muri;const latest=records.find(r=>!r.cancelled);$("latest").textContent=latest?.value||"—";$("latestSub").textContent=latest?(latest.recognized?"番号認識":"ムリ（番号不明）"):"";$("history").innerHTML=records.filter(r=>!r.cancelled).slice(0,10).map(r=>`<div class="row"><span>${esc(r.value)}${r.duplicate?` <span style="color:#d32f2f;font-weight:700;margin-left:6px;">重複</span>`:""}</span><span>${esc(r.time)}</span></div>`).join("");$("voiceBtn").textContent=listening?"🛑 音声受付停止":(cfg.mode==="EKIDEN"?"🎤 通過ナンバー開始":"🎤 フィニッシュナンバー開始");$("voiceBtn").classList.toggle("on",listening);$("status").textContent=(listening?"🟢 音声受付中":"停止中")+(sendQueue.length?` ⚠️未送信${sendQueue.length}件`:"")}
function normalizeSpeech(s){return(s||"").normalize("NFKC").replace(/\s/g,"").replace(/[ー－―—]/g,"-").replace(/の区/g,"区")}
function jpDigitsToNumber(s){const digit={零:0,〇:0,一:1,二:2,三:3,四:4,五:5,六:6,七:7,八:8,九:9,ゼロ:0,イチ:1,ニ:2,サン:3,ヨン:4,ゴ:5,ロク:6,ナナ:7,ハチ:8,キュウ:9};const units={十:10,百:100,千:1000,万:10000};let str=s.replace(/ゼロ/g,"零").replace(/イチ/g,"一").replace(/ニ/g,"二").replace(/サン/g,"三").replace(/ヨン/g,"四").replace(/ゴ/g,"五").replace(/ロク/g,"六").replace(/ナナ/g,"七").replace(/ハチ/g,"八").replace(/キュウ/g,"九");let total=0,section=0,num=0,has=false;for(const ch of str){if(digit[ch]!==undefined){num=digit[ch];has=true}else if(ch==="十"||ch==="百"||ch==="千"){section+=(num||1)*units[ch];num=0;has=true}else if(ch==="万"){section+=num;total+=section*10000;section=0;num=0;has=true}else{return null}}if(!has)return null;return total+section+num}
function parseNumber(raw){const s=normalizeSpeech(raw);if(/むり|無理/i.test(s))return"MURI";if(/キャンセル|きゃんせる|取り消し|とりけし|取消|戻す|もどす/.test(s))return"CANCEL";if(cfg.mode==="EKIDEN"){let m=s.match(/(\d{1,4})-(\d{1,2})/);if(!m)m=s.match(/(\d{1,4}).{0,3}?(\d{1,2})区/);if(!m)m=s.match(/(\d{1,4})の(\d{1,2})/);if(!m)return null;let a=Number(m[1]),b=Number(m[2]);return a>=1&&a<=9999&&b>=1&&b<=25?`${a}-${b}`:null}let d=s.replace(/[^\d]/g,"");let n=d?Number(d):null;if(!d){n=jpDigitsToNumber(s);d=n===null?"":String(n)}else if(/万|千|百|十/.test(s)){const j=jpDigitsToNumber(s);if(j!==null)n=j}return d&&n>=1&&n<=99999?String(n):null}
function add(value,recognized=true){const duplicate=recognized&&records.some(r=>!r.cancelled&&r.recognized&&r.value===value);const rec={id:Date.now()+"_"+Math.random().toString(36).substr(2,5),value,recognized,duplicate,time:now(),event:cfg.event,date:cfg.date,point:cfg.point,staff:cfg.staff,mode:cfg.mode};records.unshift(rec);recognized?ok++:muri++;if(cfg.endpoint)sendQueue.push(rec);save();render();processQueue();if(duplicate)$("status").textContent=`⚠️ ${value} は重複です`}
function cancelLast(){const i=records.findIndex(r=>!r.cancelled);if(i<0){$("status").textContent="キャンセルする登録データがありません";return}const r=records[i];r.cancelled=true;r.cancelledAt=now();r.cancelledBy="キャンセル";r.recognized?ok=Math.max(0,ok-1):muri=Math.max(0,muri-1);sendQueue=sendQueue.filter(q=>q.id!==r.id);save();render();$("status").textContent=`直前の「${r.value}」をキャンセルしました`}
async function processQueue(){if(isSending||!sendQueue.length||!cfg.endpoint||!navigator.onLine)return;isSending=true;while(sendQueue.length&&navigator.onLine){const item=sendQueue[0];try{const c=new AbortController(),t=setTimeout(()=>c.abort(),5000);await fetch(cfg.endpoint,{method:"POST",mode:"no-cors",headers:{"Content-Type":"application/json"},body:JSON.stringify(item),signal:c.signal});clearTimeout(t);sendQueue.shift();save();render()}catch{break}}isSending=false}
function registerManual(){const v=parseNumber($("numberInput").value.trim());if(v==="CANCEL"){cancelLast();$("numberInput").value="";return}if(!v){alert(cfg.mode==="EKIDEN"?"駅伝は 125-3（1～9999×1～25区）で入力してください。":"1～99999の番号を入力してください。");return}add(v==="MURI"?"ムリ":v,v!=="MURI");$("numberInput").value="";$("numberInput").focus()}
function startRecognition(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){$("status").textContent="このブラウザでは音声認識を利用できません。直接入力をご利用ください。";return}if(listening){stopRecognition();return}listening=true;render();startOne()}
function startOne(){if(!listening)return;const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR)return;try{if(recognition){recognition.onend=null;recognition.onerror=null;try{recognition.abort()}catch{}}recognition=new SR();recognition.lang="ja-JP";recognition.interimResults=false;recognition.continuous=false;recognition.maxAlternatives=5;recognition.onresult=e=>{const alts=[...e.results[0]].map(x=>x.transcript);let v=null;for(const x of alts){v=parseNumber(x);if(v)break}if(v==="CANCEL")cancelLast();else if(v==="MURI")add("ムリ",false);else if(v)add(v,true);else $("status").textContent="聞き取りましたが番号判定できません。もう一度。"};recognition.onerror=e=>{if(listening&&e.error!=="aborted")$("status").textContent=`音声エラー：${e.error} （直接入力も使用できます）`};recognition.onend=()=>{if(listening)restartTimer=setTimeout(startOne,200)};recognition.start()}catch{if(listening)restartTimer=setTimeout(startOne,500)}}
function stopRecognition(){listening=false;clearTimeout(restartTimer);if(recognition){recognition.onend=null;try{recognition.stop()}catch{}recognition=null}render()}
function openSettings(){$("sEvent").value=cfg.event;$("sDate").value=cfg.date;$("sMode").value=cfg.mode;$("sPoint").value=cfg.point;$("sStaff").value=cfg.staff;$("sTop").value=cfg.top;$("sEndpoint").value=cfg.endpoint;$("settingsPanel").hidden=false}function doCloseSettings(){$("settingsPanel").hidden=true}function doSaveSettings(){cfg={event:$("sEvent").value||"大会名未設定",date:$("sDate").value,mode:$("sMode").value,point:$("sPoint").value||"地点未設定",staff:$("sStaff").value,top:$("sTop").value,endpoint:$("sEndpoint").value};save();render();doCloseSettings()}
function countdownText(){if(!cfg.top)return"";const[h,m,s]=cfg.top.split(":").map(Number);if(!Number.isFinite(h)||!Number.isFinite(m))return"";const t=new Date();t.setHours(h,m,s||0,0);let d=t-Date.now(),past=d<0;d=Math.abs(d);const sec=Math.floor(d/1000);return past?`経過 ${Math.floor(sec/60)}:${String(sec%60).padStart(2,"0")}`:`あと ${Math.floor(sec/60)}:${String(sec%60).padStart(2,"0")}`}
$("voiceBtn").onclick=startRecognition;$("registerBtn").onclick=registerManual;$("muriBtn").onclick=()=>add("ムリ",false);$("numberInput").addEventListener("keydown",e=>{if(e.key==="Enter")registerManual()});$("settingsBtn").onclick=openSettings;$("closeSettings").onclick=doCloseSettings;$("saveSettings").onclick=doSaveSettings;$("clearRecordsBtn").onclick=()=>{if(confirm("登録されている番号データをすべて削除します。\nこの操作は元に戻せません。\n大会名・開催日・地点名・担当者などの設定は残ります。\n\n本当に削除しますか？")){records=[];sendQueue=[];ok=0;muri=0;save();render();$("status").textContent="登録データを全消去しました"}};$("cancelLastBtn")?.addEventListener("click",cancelLast);
window.addEventListener("online",()=>{render();processQueue()});window.addEventListener("offline",render);setInterval(processQueue,15000);setInterval(()=>{if(cfg.top)updateCountdown()},1000);window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredInstall=e;$("installBtn").hidden=false});$("installBtn").onclick=async()=>{if(deferredInstall){deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null;$("installBtn").hidden=true}};if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js").catch(()=>{});load();